## Importing neccesary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier

from sklearn.metrics import accuracy_score, confusion_matrix

## Importing Dataset

In [2]:
df = pd.read_csv(r'C:\Users\chsad\Documents\Mini project\dataset.csv')

In [3]:
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 346.0+ KB


### Removing Null values

In [5]:
df.fillna(0)

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                          0   
2      nodal_skin_eruptions    dischromic _patches                          0   
3                 skin_rash    dischromic _patches                          0   
4                 skin_rash   nodal_skin_eruptions                          0   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                         0                    0         0         0   
1                         0                    0         0         0   
2                         0                    0         0         0   
3                         0                    0         0         0   
4                         0                    0         0         0   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness         0         0   
4916                      0                    0         0         0   
4917                      0                    0         0         0   
4918   small_dents_in_nails   inflammatory_nails         0         0   
4919      yellow_crust_ooze                    0         0         0   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0            0          0          0          0          0          0   
1            0          0          0          0          0          0   
2            0          0          0          0          0          0   
3            0          0          0          0          0          0   
4            0          0          0          0          0          0   
...        ...        ...        ...        ...        ...        ...   
4915         0          0          0          0          0          0   
4916         0          0          0          0          0          0   
4917         0          0          0          0          0          0   
4918         0          0          0          0          0          0   
4919         0          0          0          0          0          0   

     Symptom_15 Symptom_16 Symptom_17  
0             0          0          0  
1             0          0          0  
2             0          0          0  
3             0          0          0  
4             0          0          0  
...         ...        ...        ...  
4915          0          0          0  
4916          0          0          0  
4917          0          0          0  
4918          0          0          0  
4919          0          0    

In [6]:
Y_dt= df["Disease"].unique()
Y_dt

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

## Preprocessing

In [7]:
for col in df.columns:
    print(col, ':', len(df[col].unique()),'labels')
    
    

pd.get_dummies(df, drop_first=True).shape

Disease : 41 labels
Symptom_1 : 34 labels
Symptom_2 : 48 labels
Symptom_3 : 54 labels
Symptom_4 : 51 labels
Symptom_5 : 39 labels
Symptom_6 : 33 labels
Symptom_7 : 27 labels
Symptom_8 : 22 labels
Symptom_9 : 23 labels
Symptom_10 : 22 labels
Symptom_11 : 19 labels
Symptom_12 : 12 labels
Symptom_13 : 9 labels
Symptom_14 : 5 labels
Symptom_15 : 4 labels
Symptom_16 : 4 labels
Symptom_17 : 2 labels


(4920, 417)

In [8]:
pd.get_dummies(df, drop_first=True).shape

(4920, 417)

In [9]:
symptoms_1 = [x for x in df.Symptom_1.value_counts().sort_values(ascending=False).head(34).index]
symptoms_2 = [x for x in df.Symptom_2.value_counts().sort_values(ascending=False).head(40).index]
symptoms_3 = [x for x in df.Symptom_3.value_counts().sort_values(ascending=False).head(54).index]
symptoms_4 = [x for x in df.Symptom_4.value_counts().sort_values(ascending=False).head(50).index]
#symptoms_5 = [x for x in df.Symptom_5.value_counts().sort_values(ascending=False).head(35).index]

In [10]:
symptoms = symptoms_1 + symptoms_2 + symptoms_3 + symptoms_4

def unique(symptoms):
    unique_list = []
    
    for x in symptoms:
        if x not in unique_list:
            unique_list.append(x)
    return unique_list

symptoms = unique(symptoms)

In [11]:
for label in symptoms_1:
    df[label] = np.where(df['Symptom_1'] == label, 1, 0)
    
for label in symptoms_2:
    df[label] = np.where(df['Symptom_2'] == label, 1, 0)
    

for label in symptoms_3:
    df[label] = np.where(df['Symptom_3'] == label, 1, 0)
    
for label in symptoms_4:
    df[label] = np.where(df['Symptom_4'] == label, 1, 0)
    
#for label in symptoms_5:
    #df[label] = np.where(df['Symptom_5'] == label, 1, 0)      
dt = df[['Disease']+ symptoms ]
dt


Disease   vomiting   fatigue  itching  \
0                            Fungal infection          0         0        1   
1                            Fungal infection          0         0        0   
2                            Fungal infection          0         0        1   
3                            Fungal infection          0         0        1   
4                            Fungal infection          0         0        1   
...                                       ...        ...       ...      ...   
4915  (vertigo) Paroymsal  Positional Vertigo          0         0        0   
4916                                     Acne          0         0        0   
4917                  Urinary tract infection          0         0        0   
4918                                Psoriasis          0         0        0   
4919                                 Impetigo          0         0        0   

       skin_rash   chills   joint_pain   continuous_sneezing   headache  \
0              1        0            0                     0          0   
1              0        0            0                     0          0   
2              0        0            0                     0          0   
3              1        0            0                     0          0   
4              1        0            0                     0          0   
...          ...      ...          ...                   ...        ...   
4915           0        0            0                     0          0   
4916           0        0            0                     0          0   
4917           0        0            0                     0          0   
4918           0        0            0                     0          0   
4919           0        0            0                     0          0   

       acidity  ...   passage_of_gases   family_history   swollen_legs  \
0            0  ...                  0                0              0   
1            0  ...                  0                0              0   
2            0  ...                  0                0              0   
3            0  ...                  0                0              0   
4            0  ...                  0                0              0   
...        ...  ...                ...              ...            ...   
4915         0  ...                  0                0              0   
4916         0  ...                  0                0              0   
4917         0  ...                  0                0              0   
4918         0  ...                  0                0              0   
4919         0  ...                  0                0              0   

       painful_walking   irritation_in_anus   excessive_hunger  \
0                    0                    0                  0   
1                    0                    0                  0   
2                    0                    0                  0   
3                    0                    0                  0   
4                    0                    0                  0   
...                ...                  ...                ...   
4915                 0                    0                  0   
4916                 0                    0                  0   
4917                 0                    0                  0   
4918                 0                    0                  0   
4919                 0                    0                  0   

       distention_of_abdomen   yellowing_of_eyes   irregular_sugar_level  \
0                          0                   0                       0   
1                          0                   0                       0   
2                          0                   0                       0   
3                          0                   0                       0   
4                          0                   0                       0   
...                      ...                 ...  

In [12]:
labelencoder = LabelEncoder()
dt['Disease']= labelencoder.fit_transform(dt['Disease'])

y_encode_disease = dt['Disease']
dt

<ipython-input-12-4bdb2a485548>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt['Disease']= labelencoder.fit_transform(dt['Disease'])


Disease   vomiting   fatigue  itching   skin_rash   chills   joint_pain  \
0          15          0         0        1           1        0            0   
1          15          0         0        0           0        0            0   
2          15          0         0        1           0        0            0   
3          15          0         0        1           1        0            0   
4          15          0         0        1           1        0            0   
...       ...        ...       ...      ...         ...      ...          ...   
4915        0          0         0        0           0        0            0   
4916        2          0         0        0           0        0            0   
4917       38          0         0        0           0        0            0   
4918       35          0         0        0           0        0            0   
4919       27          0         0        0           0        0            0   

       continuous_sneezing   headache   acidity  ...   passage_of_gases  \
0                        0          0         0  ...                  0   
1                        0          0         0  ...                  0   
2                        0          0         0  ...                  0   
3                        0          0         0  ...                  0   
4                        0          0         0  ...                  0   
...                    ...        ...       ...  ...                ...   
4915                     0          0         0  ...                  0   
4916                     0          0         0  ...                  0   
4917                     0          0         0  ...                  0   
4918                     0          0         0  ...                  0   
4919                     0          0         0  ...                  0   

       family_history   swollen_legs   painful_walking   irritation_in_anus  \
0                   0              0                 0                    0   
1                   0              0                 0                    0   
2                   0              0                 0                    0   
3                   0              0                 0                    0   
4                   0              0                 0                    0   
...               ...            ...               ...                  ...   
4915                0              0                 0                    0   
4916                0              0                 0                    0   
4917                0              0                 0                    0   
4918                0              0                 0                    0   
4919                0              0                 0                    0   

       excessive_hunger   distention_of_abdomen   yellowing_of_eyes  \
0                     0                       0                   0   
1                     0                       0                   0   
2                     0                       0                   0   
3                     0                       0                   0   
4                     0                       0                   0   
...                 ...                     ...                 ...   
4915                  0                       0                   0   
4916                  0                       0                   0   
4917                  0                       0                   0   
4918                  0                       0                   0   
4919                  0                       0                   0   

       irregular_sugar_level   small_dents_in_nails  
0                          0                      0  
1                          0                      0  
2                          0                      0  
3                          0                      0  
4                          0                      0  
...   

In [13]:
y_encode_disease_unique = y_encode_disease.unique()
y_encode_disease_unique

array([15,  4, 16,  9, 14, 33,  1, 12, 17,  6, 23, 30,  7, 32, 28, 29,  8,
       11, 37, 40, 19, 20, 21, 22,  3, 36, 10, 34, 13, 18, 39, 26, 24, 25,
       31,  5,  0,  2, 38, 35, 27])

In [14]:
Y= dt['Disease']
X= dt.drop('Disease', axis=1)

### Standard feature scaling

In [15]:
ss = StandardScaler()
X = ss.fit_transform(X)

## Train_Test_split

In [16]:
x_train,x_test,y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state =50)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3444, 86), (1476, 86), (3444,), (1476,))

## Decision Tree Classifier

In [17]:
dtree = DecisionTreeClassifier()
dtree.fit(x_train, y_train)

DecisionTreeClassifier()

In [18]:
dtree_pred = dtree.predict(x_test)

In [19]:
dtree_pred, dtree_pred.shape

(array([26, 28, 32, ..., 26,  4, 39]), (1476,))

In [20]:
accuracy_score(y_test, dtree_pred)

0.8882113821138211

In [21]:
confusion_matrix(y_test, dtree_pred)

array([[24,  0,  0, ...,  0,  0,  0],
       [ 0, 30,  0, ...,  0,  0,  0],
       [ 0,  0, 30, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 34,  0,  0],
       [ 0,  0,  0, ...,  0, 34,  0],
       [ 0,  0,  0, ...,  0,  0, 26]], dtype=int64)

## Random Forest classifier

In [22]:
rfc = RandomForestClassifier(n_estimators=300)
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=300)

In [23]:
rfc_pred = rfc.predict(x_test)

In [24]:
rfc_pred

array([26, 28, 32, ..., 26,  4, 39])

In [25]:
accuracy_score(y_test, rfc_pred)

0.8882113821138211

In [26]:
confusion_matrix(y_test, rfc_pred)

array([[24,  0,  0, ...,  0,  0,  0],
       [ 0, 30,  0, ...,  0,  0,  0],
       [ 0,  0, 30, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 34,  0,  0],
       [ 0,  0,  0, ...,  0, 34,  0],
       [ 0,  0,  0, ...,  0,  0, 26]], dtype=int64)

## Bagging Classifier

In [27]:
bg = BaggingClassifier(DecisionTreeClassifier(), max_samples=0.5, max_features = 1.0, n_estimators=25)
bg.fit(x_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.5,
                  n_estimators=25)

In [28]:
bg_pred = bg.predict(x_test)
bg_pred

array([26, 28, 32, ..., 26,  4, 39])

In [29]:
bg.score(x_test, y_test)

0.8882113821138211

In [30]:
bg.score(y_test, bg_pred)

ValueError: Expected 2D array, got 1D array instead:
array=[26 28 18 ... 26  4 39].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

## Boosting Classifier

In [ ]:
ada =AdaBoostClassifier(DecisionTreeClassifier(), n_estimators=10, learning_rate=1)
ada.fit(x_train, y_train)

In [ ]:
ada.predict(x_test)

In [ ]:
ada.score(x_test, y_test)

# Frontend GUI

In [ ]:
from tkinter import *
import os

from PIL import ImageTk, Image

In [ ]:
def Take_input():
    inp = input_text.get("1.0", "end-1c")
    #print(inp)
    list1= []
    list1 = [x for x in inp.split(',')]
    #print(list1)
    list2 = []
    
    for x in symptoms:
        if x in list1:
            list2.append(1)
        else:
            list2.append(0)
    
    #print(list2)
    dis_pred= dtree.predict([list2])
    #print(dis_pred)
    
    y_disease_list = y_encode_disease_unique.tolist()
    #print(y_disease_list)
    y_dis = y_disease_list.index(dis_pred[0])
    #print(y_dis)
    #print(Y_dt[y_dis])
    
    Label(screen, text=Y_dt[y_dis], font={"calibri", 16}).pack()

In [ ]:
def main_screen():
    global screen
    screen = Tk()
    
    global input_text
    screen.geometry("300x250")
    
    screen.title("Disease prediction by symptoms")
    Label(text="Disease Prediction by Symptoms", width="200",height="5",fg="yellow",bg="grey" ,font={"calibri", 100}).pack()
    Label(text="").pack()
    
    img = Image.open(r"C:\Users\chsad\Documents\Mini project\Prescription.jpg")
    test=ImageTk.PhotoImage(img)
    label1 = Label(image =test)
    label1.image = test
    label1.place(x=30, y=120) #x=30 y=120
    
    
    Label(text="Symptoms:", width="30",height="2",fg="Black", font = {"Times new roman", 16}).pack()
    input_text = Text(screen, height=10, width=35)
    input_text.pack()
    Label(text="").pack()
    
    Button(screen, text="Submit", width="15", height="2", command = Take_input).pack()
    Label(text="").pack()
    screen.mainloop()

In [ ]:
main_screen()